### ISSUE TITLE
DB integration

### ISSUE THREAD

**Issue by saskodh** [saskodh/framework-showcase#1]
***1 Upvote*** ## Background ##
For our showcase project (simple todo web app) we need to add a persistence layer. Because it's a showcase we will not add just one but two databases, a SQL(postgresql) one and NoSQL(mongodb) one.
The idea is to try to integrate with two different databases and also try utility libraries that can be used with them and see how we can do those integrations easier with our framework.

## Task ##
- install local instance of the PostgreSQL db
- integrate PostgreSQL in the project ([pg](https://www.npmjs.com/package/pg))
- install local instance of the Mongo db
- integrate Mongo db in the project ([mongodb](https://www.npmjs.com/package/mongodb))
- define TodoRepository interface that will be used for persisting the todos
- add Mongo and PostgreSQL implementations for the TodoRepository
- check libraries that can be used on top of these db drivers
  * for PostgreSQL
    * query builder ([knex](https://www.npmjs.com/package/knex))
    * ORM ([sequelize](https://www.npmjs.com/package/sequelize), [bookshelf](https://www.npmjs.com/package/bookshelf)..)
  * for Mongo
    * ODM ([mongoose](https://www.npmjs.com/package/mongoose)..)

**Comment by draganAndonovski** [comment]
.
